# Generated by Django 5.1.7 on 2025-03-13 22:10

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingphoto',
            name='image',
            field=models.ImageField(default=None, upload_to=post.models.listing_directory_path),
            preserve_default=False,
        ),
    ]
