# Generated by Django 5.1.7 on 2025-03-13 22:22

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_listingphoto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingphoto',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to=post.models.listing_directory_path),
        ),
    ]
