# Generated by Django 5.1.7 on 2025-03-14 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_listingphoto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingphoto',
            name='image',
        ),
    ]
