# Generated by Django 5.1.7 on 2025-03-15 21:34

import authy.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0009_remove_listing_latitude_value_validation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=authy.models.profile_directory_path)),
                ('phone_no', models.CharField(blank=True, max_length=10)),
                ('address', models.CharField(blank=True, max_length=256)),
                ('email_field', models.EmailField(blank=True, max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('women', 'Women'), ('others', 'Others')], max_length=10)),
                ('co_hosts', models.ManyToManyField(blank=True, related_name='co_hosted_by', to='authy.profile')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='post.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('email_field__endswith', '@gmail.com')), name='email_field_validation', violation_error_message='enter valid email id !')],
            },
        ),
    ]
