# Generated by Django 5.1.7 on 2025-03-16 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='co_hosts',
        ),
        migrations.AddField(
            model_name='profile',
            name='co_hosts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='co_hosted_by', to='authy.profile'),
        ),
    ]
