# Generated by Django 5.1.7 on 2025-03-19 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0004_alter_profile_user'),
        ('post', '0009_remove_listing_latitude_value_validation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='post.listing'),
        ),
    ]
